GET
/api/2.0/accounts/{account_id}/networks/{network_id}
Gets a Databricks network configuration, which represents an AWS VPC and its resources.  This requires a pre-existing VPC and subnets.
For VPC requirements, see
Customer-managed VPC
.
This operation is available only if your account is on the E2 version of the platform.
Path parameters
code: account_id
required
uuid
Databricks account ID of any type. For non-E2 account types, get your account ID from the
Accounts Console
.
code: network_id
required
uuid
Databricks Account API network configuration ID.
Responses
200
The network configuration was successfully returned.
The network configuration was successfully returned.
code: network_id
uuid
The Databricks network configuration ID.
code: network_name
string
[ 4 .. 256 ] characters
Example
code: "my-databricks-network"
The human-readable name of the network configuration.
code: vpc_id
string
The ID of the VPC associated with this network configuration. VPC IDs can be used in multiple networks.
code: subnet_ids
Array of string
>= 2 characters
code: security_group_ids
Array of string
[ 1 .. 5 ] characters
code: vpc_status
string
Enum:
code: UNATTACHED | VALID | BROKEN | WARNED
The status of this network configuration object in terms of its use in a workspace:
code: UNATTACHED
: Unattached.
code: VALID
: Valid.
code: BROKEN
: Broken.
code: WARNED
: Warned.
code: warning_messages
Array of object
Array of warning messages about the network configuration.
Array [
code: warning_type
string
Enum:
code: subnet | securityGroup
The AWS resource associated with this warning: a subnet or a security group.
code: warning_message
string
Details of the warning.
]
code: error_messages
Array of object
Array of error messages about the network configuration.
Array [
code: error_type
string
Enum:
code: credentials | vpc | subnet | securityGroup | networkAcl
The AWS resource associated with this error: credentials, VPC, subnet, security group, or network ACL.
code: error_message
string
Details of the error.
]
code: workspace_id
int64
Example
code: 1614665312930232
Workspace ID associated with this network configuration.
code: account_id
uuid
The Databricks account ID associated with this network configuration.
code: creation_time
int64
Example
code: 1643668346544
Time in epoch milliseconds when the network was created.
code: vpc_endpoints
object
If specified, contains the VPC endpoints used to allow cluster communication from this VPC over
AWS PrivateLink
.
code: rest_api
required
Array of uuid
The VPC endpoint ID used by this network to access the Databricks REST API. Databricks clusters make calls to our REST API as part of cluster creation, mlflow tracking, and many other features. Thus, this is required even if your workspace allows public access to the REST API.
This is a list type for future compatibility, but currently only one VPC endpoint ID should be supplied.
Note
: This is the Databricks-specific ID of the VPC endpoint object in the Account API, not the AWS VPC endpoint ID that you see for your endpoint in the AWS Console.
code: dataplane_relay
required
Array of uuid
The VPC endpoint ID used by this network to access the Databricks secure cluster connectivity relay. See
Secure Cluster Connectivity
.
This is a list type for future compatibility, but currently only one VPC endpoint ID should be supplied.
Note
: This is the Databricks-specific ID of the VPC endpoint object in the Account API, not the AWS VPC endpoint ID that you see for your endpoint in the AWS Console.
This method might return the following HTTP codes: 401, 404, 500
Error responses are returned in the following format:
{
"error_code"
:
"Error code"
,
"message"
:
"Human-readable error message."
}
Possible error codes:
HTTP code
error_code
Description
401
UNAUTHORIZED
The request does not have valid authentication credentials for the operation.
404
NOT_FOUND
Operation was performed on a resource that does not exist.
500
INTERNAL_SERVER_ERROR
Internal error.