{
 "/api/2.0/accounts/{account_id}/credentials": {
  "get": {
   "operationId": "credentials-list",
   "externalDocs": {
    "url": "https://docs.databricks.com/api/account/credentials/list"
   },
   "x-stackQL-resource": "credentials",
   "x-stackQL-method": "list",
   "x-stackQL-verb": "select",
   "x-numReqParams": 1,
   "parameters": [
    {
     "name": "account_id",
     "required": true,
     "description": "(uuid) Databricks account ID of any type. For non-E2 account types, get your account ID from the ",
     "in": "path"
    }
   ],
   "responses": {
    "200": {
     "description": "Credential configurations were returned successfully.",
     "content": {
      "application/json": {
       "schema": {
        "type": "array",
        "items": {
         "type": "object",
         "properties": {
          "credentials_id": {
           "type": "string"
          },
          "credentials_name": {
           "type": "string"
          },
          "aws_credentials": {
           "type": "object",
           "properties": {
            "sts_role": {
             "type": "object",
             "properties": {
              "role_arn": {
               "type": "string"
              },
              "external_id": {
               "type": "string"
              }
             }
            }
           }
          },
          "account_id": {
           "type": "string"
          },
          "creation_time": {
           "type": "integer"
          }
         }
        }
       }
      }
     }
    },
    "401": {
     "description": "The request does not have valid authentication credentials for the operation."
    },
    "404": {
     "description": "Operation was performed on a resource that does not exist."
    },
    "500": {
     "description": "Internal error."
    }
   },
   "description": "Gets all Databricks credential configurations associated with an account specified by ID."
  }
 }
}